name: Compile LaTeX
on: [ push ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build main.tex
        run: latexmk -pdf -output-directory=out main.tex

      - name: Build test1.tex
        run: latexmk -pdf -output-directory=out test1.tex

      - name: Build test2.tex
        run: latexmk -pdf -output-directory=out test2.tex

      - name: Build test3.tex
        run: latexmk -pdf -output-directory=out test3.tex

      - name: Build test4.tex
        run: latexmk -pdf -output-directory=out test4.tex

      - name: Build test5.tex
        run: latexmk -pdf -output-directory=out test5.tex

      - name: Upload all documents
        uses: actions/upload-artifact@v4
        with:
          name: compiled-documents
          path: out/*.pdf