name: Compile LaTeX
on: [ push ]
jobs:
  container:
    runs-on: ubuntu-latest
    container: kjarosh/latex:2024.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build using latexmk
        run: latexmk -pdf -output-directory=out main.tex

      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: main-document
          path: out/main.pdf